Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1968, in __call__
  File "main.py", line 209, in insert
IndexError: string index out of range
----------Above 2024-10-06 09:36:27----------

